Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2023.10.07`](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.10.07) to [`2023.10.13`](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.10.13).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.10.13)
=> update yt-dlp from 2023.10.07 to 2023.10.13

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2023.10.13`](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.10.13) to [`2023.11.16`](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.11.16).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.11.16)
=> update yt-dlp from 2023.10.13 to 2023.11.16

Makefile, builder.gen.go, builder.gen_test.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.03.10`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.03.10) to [`2024.04.09`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.04.09).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.04.09)
=> update yt-dlp from 2024.03.10 to 2024.04.09

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.07.02`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.02) to [`2024.07.07`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.07).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.07)
=> update yt-dlp from 2024.07.02 to 2024.07.07

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.07.07`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.07) to [`2024.07.08`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.08).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.08)
=> update yt-dlp from 2024.07.07 to 2024.07.08

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.07.08`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.08) to [`2024.07.09`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.09).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.09)
=> update yt-dlp from 2024.07.08 to 2024.07.09

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.07.09`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.09) to [`2024.07.16`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.16).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.16)
=> update yt-dlp from 2024.07.09 to 2024.07.16

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.07.16`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.16) to [`2024.07.25`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.25).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.25)
=> update yt-dlp from 2024.07.16 to 2024.07.25

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.07.25`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.25) to [`2024.08.01`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.08.01).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.08.01)
=> update yt-dlp from 2024.07.25 to 2024.08.01

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.08.01`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.08.01) to [`2024.08.06`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.08.06).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.08.06)
=> update yt-dlp from 2024.08.01 to 2024.08.06

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.09.27`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.09.27) to [`2024.10.07`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.10.07).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.10.07)
=> update yt-dlp from 2024.09.27 to 2024.10.07

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.10.22`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.10.22) to [`2024.11.04`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.11.04).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.11.04)
=> update yt-dlp from 2024.10.22 to 2024.11.04

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.11.18`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.11.18) to [`2024.12.03`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.03).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.03)
=> update yt-dlp from 2024.11.18 to 2024.12.03

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.12.03`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.03) to [`2024.12.06`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.06).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.06)
=> update yt-dlp from 2024.12.03 to 2024.12.06

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.12.13`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.13) to [`2024.12.23`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.23).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.23)
=> update yt-dlp from 2024.12.13 to 2024.12.23

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2024.12.23`](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.23) to [`2025.01.12`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.12).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.12)
=> update yt-dlp from 2024.12.23 to 2025.01.12

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2025.01.12`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.12) to [`2025.01.15`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.15).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.15)
=> update yt-dlp from 2025.01.12 to 2025.01.15

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2025.01.15`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.15) to [`2025.01.26`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.26).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.26)
=> update yt-dlp from 2025.01.15 to 2025.01.26

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2025.01.26`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.26) to [`2025.02.19`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.02.19).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.02.19)
=> update yt-dlp from 2025.01.26 to 2025.02.19

Makefile, builder.gen.go, builder.gen_test.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2025.02.19`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.02.19) to [`2025.03.21`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.21).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.21)
=> update yt-dlp from 2025.02.19 to 2025.03.21

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2025.03.21`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.21) to [`2025.03.25`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.25).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.25)
=> update yt-dlp from 2025.03.21 to 2025.03.25

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2025.03.25`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.25) to [`2025.03.26`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.26).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.26)
=> update yt-dlp from 2025.03.25 to 2025.03.26

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2025.03.26`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.26) to [`2025.03.27`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.27).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.27)
=> update yt-dlp from 2025.03.26 to 2025.03.27

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2025.03.27`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.27) to [`2025.03.31`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.31).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.31)
=> update yt-dlp from 2025.03.27 to 2025.03.31

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2025.06.25`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.06.25) to [`2025.06.30`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.06.30).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.06.30)
=> update yt-dlp from 2025.06.25 to 2025.06.30

Makefile, builder.gen.go, constants.gen.go, optiondata/optiondata.gen.go
- Bumping **version** from [`2025.08.27`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.08.27) to [`2025.09.05`](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.09.05).
Release notes: [link](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.09.05)
=> update yt-dlp from 2025.08.27 to 2025.09.05
